-- Eine große Firma entnimmt regelmäßig Wasserproben (Brunnen, See, Fließgewässer) an
-- verschiedenen Orten. Die Proben werden von drei Personen bzw. Teams entnommen, die dazu eine
-- spezielle Ausrüstung und Software verwenden. Da die Probennahme auch an entlegenen Orten
-- erfolgen kann, verwendet die Software eine interne Datenbank, die regelmäßig mit der Zentrale
-- synchronisiert wird. Jeder Probe soll bereits bei der Entnahme eine eindeutige Nummer zur
-- Identifikation zugeordnet werden.
-- Legen Sie dafür eine Tabelle „Probe“ (Proben-ID, Zeitpunkt der Probenname, Probentyp,
-- Kommentar) an. Erstellen Sie weitere Datenbank-Objekte, um Identifikationsnummern pro Team
-- erzeugen zu können. Gehen Sie bei der Vergabe der Identifikation so vor, dass sie zukünftig sofort
-- ablesen können, welches Team die Probe entnommen hat.
-- Zeigen Sie beispielhaft, wie die drei Personen/Teams Datensätze einfügen können. Fragen Sie diese
-- Daten auch ab.
CREATE TABLE Probe (
    Probe_id NUMBER PRIMARY KEY,
    Probe_Zeitpunkt DATE,
    ProbeTyp VARCHAR(20),
    Kommentar VARCHAR(50),
    Identifikationsnummer NUMBER
    CONSTRAINT TEAM_IDENTIFIKATIONUMMER_FK REFERENCES TEAM(Identifikationsnummer)
);

CREATE TABLE TEAM
(
    Identifikationsnummer INT GENERATED BY DEFAULT AS IDENTITY
    ( START WITH 200 INCREMENT BY 1
    MINVALUE 200 MAXVALUE 100000) PRIMARY KEY ,
    Name Varchar2(20)
);

CREATE SEQUENCE Probe_sq1
START WITH 1000
INCREMENT BY 1
MAXVALUE 2000
CACHE 10;

CREATE SEQUENCE Probe_sq2
START WITH 2001
INCREMENT BY 1
MAXVALUE 3000
CACHE 10;

CREATE SEQUENCE Probe_sq3
START WITH 3001
INCREMENT BY 1
MAXVALUE 4000
CACHE 10;

INSERT INTO TEAM(Identifikationsnummer,Name)
VALUES(DEFAULT,'TEAM1');
INSERT INTO TEAM(Identifikationsnummer,Name)
VALUES(DEFAULT,'TEAM2');

SELECT * FROM TEAM;

INSERT INTO Probe
VALUES (Probe_sq1.nextval, SYSDATE, 'SEE', 'SEE PROBE 1',200);

INSERT INTO Probe
VALUES (Probe_sq1.nextval, SYSDATE, 'SEE', 'SEE PROBE 2',200);

INSERT INTO Probe
VALUES (Probe_sq2.nextval, SYSDATE, 'Fließgewässer', 'Fließgewässer Probe 1',200);

INSERT INTO Probe
VALUES (Probe_sq2.nextval, SYSDATE, 'Fließgewässer', 'Fließgewässer Probe 2',201);

INSERT INTO Probe
VALUES (Probe_sq2.nextval, SYSDATE, 'Fließgewässer', 'Fließgewässer Probe 3',201);

INSERT INTO Probe
VALUES (Probe_sq3.nextval, SYSDATE, 'Brunnen', 'Brunnen Probe 1',201);

INSERT INTO Probe
VALUES (Probe_sq3.nextval, SYSDATE, 'Brunnen', 'Brunnen Probe 2',201);

INSERT INTO Probe
VALUES (Probe_sq3.nextval, SYSDATE, 'Brunnen', 'Brunnen Probe 3',201);


SELECT *
FROM Probe;

drop table PROBE cascade constraints;
drop sequence PROBE_SQ1;
drop sequence PROBE_SQ2;
drop sequence PROBE_SQ3;

