SELECT COUNT(SID)
FROM V$SESSION
WHERE SCHEMANAME <> 'SYS';
-- 2. Erstellen Sie eine Tabelle monitor_sessions für die Protokollierung der Abfrage über die
-- Anzahl der Sessions. Fügen Sie zur Anzahl auch noch einen Zeitstempel hinzu und sehen Sie
-- auch eine Spalte für das Einfügen eines Primärschlüssels vor. Legen Sie dafür eine eigene
-- Sequenz an und verwenden Sie diese.
CREATE TABLE monitor_sessions (
    MS_ID INT GENERATED BY DEFAULT AS IDENTITY
    ( START WITH 200 INCREMENT BY 1
    MINVALUE 200 MAXVALUE 100000) PRIMARY KEY,
    COUNT NUMBER,
    LAST_CHECK DATE
);

-- 3. Erstellen Sie ein Insert-Skript, das Sie aufrufen können und die Anzahl der offenen BenutzerSessions in Ihre
-- Logging-Tabelle einfügt. Rufen Sie das Skript zu verschiedenen Zeitpunkten auf.

INSERT INTO monitor_sessions(MS_ID,COUNT,LAST_CHECK)
VALUES (
DEFAULT,
(SELECT COUNT(SID)
FROM V$SESSION
WHERE SCHEMANAME <> 'SYS'),
SYSDATE
);

SELECT *
FROM monitor_sessions;
